version: '2'

services:
  fullstack-test-php:
    build: php
    working_dir: /app
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini.dist
      - ./..:/app
    networks:
      - fullstack-test-net
    command: bash -c "cp /usr/local/etc/php/php.ini.dist /usr/local/etc/php/php.ini && echo \"xdebug.remote_host=`/sbin/ip route|awk '/default/ { print $$3 }'`\" >> /usr/local/etc/php/php.ini && php-fpm"

  fullstack-test-web:
    image: nginx
    ports:
      - 80:80
    working_dir: /app
    volumes:
      - ./..:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fullstack-test-net

  fullstack-test-db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - fullstack-test-net

networks:
  fullstack-test-net:
